"""Versioned constants for ordered entity interaction chains."""

from __future__ import annotations


ENTITY_INTERACTIONS_SCHEMA = "hytalerl_entity_interactions_v2"
ENTITY_INTERACTIONS_VERSION = 2

CROSSBOW_IMPACT_CAPACITY = 16

CROSSBOW_IMPACT_NONE = 0
CROSSBOW_IMPACT_STANDARD = 1
CROSSBOW_IMPACT_BIG_ARROW = 2
CROSSBOW_IMPACT_KIND_COUNT = 3

CROSSBOW_COMBO_NONE = 0
CROSSBOW_COMBO_ONE = 1
CROSSBOW_COMBO_TWO = 2

CROSSBOW_COMBO_1_EFFECT_ID = 1621052912
CROSSBOW_COMBO_2_EFFECT_ID = 1671385769
CROSSBOW_COMBO_DURATION_SECONDS = 5.0

CROSSBOW_STANDARD_DAMAGE = 10.0
CROSSBOW_COMBO_DAMAGE = 27.0
CROSSBOW_BIG_ARROW_DAMAGE = 78.0
CROSSBOW_STANDARD_FORCE = 4.0
CROSSBOW_COMBO_FORCE = 12.0
CROSSBOW_BIG_ARROW_FORCE = 18.0
CROSSBOW_FORCE_DIRECTION = (0.0, 0.5, -1.0)

CROSSBOW_AIR_RESISTANCE = 0.99
CROSSBOW_AIR_RESISTANCE_MAX = 0.98
CROSSBOW_GROUND_RESISTANCE = 0.94
CROSSBOW_GROUND_RESISTANCE_MAX = 0.3
CROSSBOW_RESISTANCE_THRESHOLD = 3.0
CROSSBOW_RESISTANCE_STYLE_LINEAR = 0

POTION_REGEN_EFFECT_IDS = (
    1354478198,  # Potion_Health_Regen_Lesser
    497869059,  # Potion_Health_Regen_Small
    1068685643,  # Potion_Health_Regen
    2140942922,  # Potion_Health_Regen_Greater
    200537323,  # Potion_Health_Regen_Large
    1463804502,  # Potion_Stamina_Regen
)

INTERACTION_CAPABILITY_ORDERED_IMPACTS = 1 << 0
INTERACTION_CAPABILITY_CROSSBOW_COMBO = 1 << 1
INTERACTION_CAPABILITY_GAMEPLAY_EFFECT_CLEAR = 1 << 2
INTERACTION_CAPABILITY_CROSSBOW_FORCE = 1 << 3
INTERACTION_CAPABILITIES = (
    INTERACTION_CAPABILITY_ORDERED_IMPACTS
    | INTERACTION_CAPABILITY_CROSSBOW_COMBO
    | INTERACTION_CAPABILITY_GAMEPLAY_EFFECT_CLEAR
    | INTERACTION_CAPABILITY_CROSSBOW_FORCE
)

INTERACTION_FAILURE_INVALID_STATE = 1 << 0
INTERACTION_FAILURE_INVALID_COMMAND = 1 << 1
INTERACTION_FAILURE_STALE_HANDLE = 1 << 2
INTERACTION_FAILURE_UNSUPPORTED_TARGET = 1 << 3
INTERACTION_FAILURE_UPSTREAM = 1 << 4
INTERACTION_FAILURE_MECHANICS = 1 << 5
INTERACTION_FAILURE_IMPACT_OVERFLOW = 1 << 6
