"""Pinned outputs of the Hytale 0.5.7 deployable-terminal compiler."""

from __future__ import annotations

from .compiler import (
    DEPLOYABLE_DEFAULT_HEALTH,
    DEPLOYABLE_ATTACK_ENEMIES,
    DEPLOYABLE_ATTACK_FLAG_MASK,
    DeployableStatusSpec,
    ProjectileTerminalDeployableSpec,
)


DEPLOYABLE_SOURCE_PATHS = {
    "healing_totem": (
        "Server/Item/Items/Weapon/Deployable/Weapon_Deployable_Healing_Totem.json",
        "Server/ProjectileConfigs/Weapons/Deployables/Projectile_Config_Healing_Totem_Deploy.json",
        "Server/Models/Deployables/Projectiles/Healing_Totem_Projectile.json",
        "Server/Models/Deployables/Healing_Totem.json",
        "Server/Entity/HitboxCollision/HardCollision.json",
        "Server/Entity/Stats/Health.json",
        "Server/Entity/Effects/Deployables/Healing_Totem_Heal.json",
    ),
    "slowness_totem": (
        "Server/Item/Items/Weapon/Deployable/Weapon_Deployable_Slowness_Totem.json",
        "Server/ProjectileConfigs/Weapons/Deployables/Projectile_Config_Slowness_Totem_Deploy.json",
        "Server/Models/Deployables/Slowness_Totem.json",
        "Server/Models/Deployables/Slowness_Totem.json",
        "Server/Entity/HitboxCollision/HardCollision.json",
        "Server/Entity/Stats/Health.json",
        "Server/Entity/Effects/Deployables/Slowness_Totem_Slow.json",
    ),
}

DEPLOYABLE_SPECS = (
    ProjectileTerminalDeployableSpec(
        profile="healing_totem",
        asset_id="Weapon_Deployable_Healing_Totem",
        family_id=224,
        projectile_config_id="Projectile_Config_Healing_Totem_Deploy",
        deployable_id="Healing_Totem",
        cooldown_group_id="DeployableUtility",
        launch_event_seconds=0.25,
        ability_duration_seconds=0.25,
        cooldown_seconds=10.0,
        launch_force=10.0,
        gravity=15.0,
        terminal_velocity_air=50.0,
        terminal_velocity_water=15.0,
        rotation_mode="VelocityDamped",
        collision_min=(-0.1, -0.1, -0.1),
        collision_max=(0.1, 0.1, 0.1),
        projectile_lifetime_seconds=300.0,
        spawn_offset=(0.3, -0.5, -0.6),
        spawn_yaw_degrees=5.0,
        spawn_pitch_degrees=10.0,
        bounciness=0.0,
        bounce_limit=0.4,
        bounce_count=-1,
        allow_rolling=False,
        rolling_friction_factor=0.99,
        sticks_vertically=False,
        area_shape="Cylinder",
        deployable_collision_min=(-0.05, 0.0, -0.05),
        deployable_collision_max=(0.05, 1.5, 0.05),
        deployable_hard_collision=True,
        deployable_count_towards_global_limit=True,
        deployable_max_live_count=2_147_483_647,
        deployable_default_health=DEPLOYABLE_DEFAULT_HEALTH,
        area_duration_seconds=10.0,
        area_interval_seconds=0.5,
        area_start_radius=0.1,
        area_end_radius=5.0,
        area_height=2.0,
        area_radius_change_seconds=2.0,
        area_damage=0.0,
        area_damage_cause="Physical",
        area_attack_flags=DEPLOYABLE_ATTACK_FLAG_MASK,
        status=DeployableStatusSpec(
            effect_asset_id="Healing_Totem_Heal",
            duration_seconds=1.0,
            calculator_cooldown_seconds=1.0,
            healing_per_cycle=5.0,
            horizontal_speed_multiplier=1.0,
            overlap_behavior="Overwrite",
            debuff=False,
        ),
    ),
    ProjectileTerminalDeployableSpec(
        profile="slowness_totem",
        asset_id="Weapon_Deployable_Slowness_Totem",
        family_id=225,
        projectile_config_id="Projectile_Config_Slowness_Totem_Deploy",
        deployable_id="Slowness_Totem",
        cooldown_group_id="DeployableUtility",
        launch_event_seconds=0.25,
        ability_duration_seconds=0.25,
        cooldown_seconds=10.0,
        launch_force=10.0,
        gravity=15.0,
        terminal_velocity_air=50.0,
        terminal_velocity_water=15.0,
        rotation_mode="None",
        collision_min=(-0.05, 0.0, -0.05),
        collision_max=(0.05, 1.5, 0.05),
        projectile_lifetime_seconds=300.0,
        spawn_offset=(0.3, -0.5, -0.6),
        spawn_yaw_degrees=5.0,
        spawn_pitch_degrees=10.0,
        bounciness=0.9,
        bounce_limit=0.4,
        bounce_count=0,
        allow_rolling=False,
        rolling_friction_factor=0.99,
        sticks_vertically=False,
        area_shape="Sphere",
        deployable_collision_min=(-0.05, 0.0, -0.05),
        deployable_collision_max=(0.05, 1.5, 0.05),
        deployable_hard_collision=True,
        deployable_count_towards_global_limit=True,
        deployable_max_live_count=2_147_483_647,
        deployable_default_health=DEPLOYABLE_DEFAULT_HEALTH,
        area_duration_seconds=10.0,
        area_interval_seconds=0.5,
        area_start_radius=0.1,
        area_end_radius=5.0,
        area_height=2.0,
        area_radius_change_seconds=2.0,
        area_damage=0.0,
        area_damage_cause="Physical",
        area_attack_flags=DEPLOYABLE_ATTACK_ENEMIES,
        status=DeployableStatusSpec(
            effect_asset_id="Slowness_Totem_Slow",
            duration_seconds=1.0,
            calculator_cooldown_seconds=0.0,
            healing_per_cycle=0.0,
            horizontal_speed_multiplier=0.5,
            overlap_behavior="Overwrite",
            debuff=True,
        ),
    ),
)
DEPLOYABLE_PROFILE_NAMES = tuple(spec.profile for spec in DEPLOYABLE_SPECS)

assert {spec.family_id for spec in DEPLOYABLE_SPECS} == {224, 225}
assert len(set(DEPLOYABLE_PROFILE_NAMES)) == len(DEPLOYABLE_SPECS)


__all__ = [
    "DEPLOYABLE_PROFILE_NAMES",
    "DEPLOYABLE_SOURCE_PATHS",
    "DEPLOYABLE_SPECS",
]
