"""Behaviour cloning and the native-trace pipeline.

The path a native NPC demonstration takes to become a warm-started JAX policy:

``native_replay``
    Death-complete native traces rebuilt as JAX-resident replay environments.
``native_replay_cache``
    Content-addressed projection and train/eval splits over those traces.
``native_imitation``
    Conservative Arena action labels derived from native steering.
``behavior_cloning``
    Generic supervised cloning over Arena's factored action contract.
``native_transfer``
    Fail-closed warm start of the Arsenal policy from cloned weights.

``behavior_cloning`` was ``arena.training.imitation`` before this package
existed; its names are re-exported here, so ``from arena.training.imitation
import DemonstrationBatch`` still resolves.
"""

from __future__ import annotations

from arena.training.imitation.behavior_cloning import (
    BehaviorCloningConfig,
    BehaviorCloningLoss,
    BehaviorCloningMetrics,
    BehaviorCloningTrainer,
    DemonstrationBatch,
    NATIVE_HEAD_SIZES,
    ProjectedDemonstrations,
    behavior_cloning_head_accuracy,
    behavior_cloning_loss,
    demonstration_batch,
    make_behavior_cloning_trainer,
    projected_demonstrations,
)
from arena.training.imitation.native_imitation import (
    NativeNpcBehaviorLabels,
    NativeNpcDemonstrations,
    NativeNpcDuelDemonstrations,
    native_npc_demonstrations,
    native_npc_duel_demonstrations,
)
from arena.training.imitation.native_replay import (
    NATIVE_REPLAY_ABILITY_SLOT_SCHEMA,
    NATIVE_REPLAY_ACTION_SCHEMA,
    NATIVE_REPLAY_BASE_OBSERVATION_SCHEMA,
    NATIVE_REPLAY_OBSERVATION_SCHEMA,
    NATIVE_REPLAY_OBSERVATION_SCHEMAS,
    NATIVE_REPLAY_SCHEMA,
    NATIVE_REPLAY_VISUAL_SHA256,
    NATIVE_REPLAY_VISUAL_SIZE,
    NativeBehaviorPolicy,
    NativeReplayBatch,
    NativeReplayCorpus,
    NativeReplayDemonstrations,
    NativeReplaySequence,
    NativeReplaySplit,
    NativeReplayState,
    NativeReplayTensors,
    PackedNativeReplaySequence,
    build_native_replay_corpus,
    causal_opponent_row_indices,
    load_native_behavior_policy,
    load_native_replay_corpus,
    make_native_replay_environment,
    native_behavior_policy_logits,
    native_replay_ability_slot_contract_sha256,
    native_replay_action_head_coverage,
    native_replay_demonstrations,
    native_replay_ppo_config,
    native_replay_sequence,
    native_replay_tensor_sha256,
    pack_native_replay_sequence,
    sample_native_replay_rows,
    split_native_replay_corpus,
    write_native_replay_corpus,
)
from arena.training.imitation.native_replay_cache import (
    CompiledNativeReplay,
    NATIVE_REPLAY_CACHE_SCHEMA,
    compile_or_load_native_replay,
)
from arena.training.imitation.native_transfer import (
    NATIVE_ARSENAL_ABILITY_BINDING_SCHEMA,
    NATIVE_ARSENAL_ABILITY_SLOT_CONTRACT_SCHEMA,
    NATIVE_ARSENAL_ACTION_HEAD_READINESS_SCHEMA,
    NATIVE_ARSENAL_CONDITIONED_OBSERVATION_SCHEMA,
    NATIVE_ARSENAL_SHARED_DENSE_INDICES,
    NATIVE_ARSENAL_SHARED_FEATURE_LAYOUT,
    NATIVE_ARSENAL_SHARED_OBSERVATION_SCHEMA,
    NATIVE_ARSENAL_SHARED_OBSERVATION_SHA256,
    NATIVE_ARSENAL_SHARED_OBSERVATION_SIZE,
    NATIVE_ARSENAL_TRANSFERABLE_HEADS,
    NATIVE_ARSENAL_TRANSFER_SCHEMA,
    NATIVE_ARSENAL_VISUAL_CONDITIONED_OBSERVATION_SCHEMA,
    NATIVE_ARSENAL_VISUAL_DENSE_INDICES,
    NATIVE_ARSENAL_VISUAL_SHARED_DENSE_INDICES,
    NATIVE_ARSENAL_VISUAL_SHARED_FEATURE_LAYOUT,
    NATIVE_ARSENAL_VISUAL_SHARED_OBSERVATION_SCHEMA,
    NATIVE_ARSENAL_VISUAL_SHARED_OBSERVATION_SHA256,
    NATIVE_ARSENAL_VISUAL_SHARED_OBSERVATION_SIZE,
    NativeArsenalAbilityBinding,
    arsenal_conditioned_observation,
    arsenal_shared_observation,
    arsenal_visual_conditioned_observation,
    arsenal_visual_shared_observation,
    native_arsenal_ability_binding,
    native_arsenal_ability_binding_sha256,
    native_arsenal_ability_slot_contract_sha256,
    native_arsenal_action_head_readiness,
    native_arsenal_conditioned_observation_sha256,
    native_arsenal_conditioned_replay_corpus,
    native_arsenal_npc_role_ability_binding,
    native_arsenal_profile_basic_attack_binding,
    native_arsenal_shared_replay_corpus,
    native_arsenal_visual_conditioned_observation_sha256,
    native_arsenal_visual_conditioned_replay_corpus,
    native_arsenal_visual_shared_replay_corpus,
    native_behavior_observation_projector,
    transplant_native_behavior_policy,
)


__all__ = [
    "BehaviorCloningConfig",
    "BehaviorCloningLoss",
    "BehaviorCloningMetrics",
    "BehaviorCloningTrainer",
    "CompiledNativeReplay",
    "DemonstrationBatch",
    "NATIVE_ARSENAL_ABILITY_BINDING_SCHEMA",
    "NATIVE_ARSENAL_ABILITY_SLOT_CONTRACT_SCHEMA",
    "NATIVE_ARSENAL_ACTION_HEAD_READINESS_SCHEMA",
    "NATIVE_ARSENAL_CONDITIONED_OBSERVATION_SCHEMA",
    "NATIVE_ARSENAL_SHARED_DENSE_INDICES",
    "NATIVE_ARSENAL_SHARED_FEATURE_LAYOUT",
    "NATIVE_ARSENAL_SHARED_OBSERVATION_SCHEMA",
    "NATIVE_ARSENAL_SHARED_OBSERVATION_SHA256",
    "NATIVE_ARSENAL_SHARED_OBSERVATION_SIZE",
    "NATIVE_ARSENAL_TRANSFERABLE_HEADS",
    "NATIVE_ARSENAL_TRANSFER_SCHEMA",
    "NATIVE_ARSENAL_VISUAL_CONDITIONED_OBSERVATION_SCHEMA",
    "NATIVE_ARSENAL_VISUAL_DENSE_INDICES",
    "NATIVE_ARSENAL_VISUAL_SHARED_DENSE_INDICES",
    "NATIVE_ARSENAL_VISUAL_SHARED_FEATURE_LAYOUT",
    "NATIVE_ARSENAL_VISUAL_SHARED_OBSERVATION_SCHEMA",
    "NATIVE_ARSENAL_VISUAL_SHARED_OBSERVATION_SHA256",
    "NATIVE_ARSENAL_VISUAL_SHARED_OBSERVATION_SIZE",
    "NATIVE_HEAD_SIZES",
    "NATIVE_REPLAY_ABILITY_SLOT_SCHEMA",
    "NATIVE_REPLAY_ACTION_SCHEMA",
    "NATIVE_REPLAY_BASE_OBSERVATION_SCHEMA",
    "NATIVE_REPLAY_CACHE_SCHEMA",
    "NATIVE_REPLAY_OBSERVATION_SCHEMA",
    "NATIVE_REPLAY_OBSERVATION_SCHEMAS",
    "NATIVE_REPLAY_SCHEMA",
    "NATIVE_REPLAY_VISUAL_SHA256",
    "NATIVE_REPLAY_VISUAL_SIZE",
    "NativeArsenalAbilityBinding",
    "NativeBehaviorPolicy",
    "NativeNpcBehaviorLabels",
    "NativeNpcDemonstrations",
    "NativeNpcDuelDemonstrations",
    "NativeReplayBatch",
    "NativeReplayCorpus",
    "NativeReplayDemonstrations",
    "NativeReplaySequence",
    "NativeReplaySplit",
    "NativeReplayState",
    "NativeReplayTensors",
    "PackedNativeReplaySequence",
    "ProjectedDemonstrations",
    "arsenal_conditioned_observation",
    "arsenal_shared_observation",
    "arsenal_visual_conditioned_observation",
    "arsenal_visual_shared_observation",
    "behavior_cloning_head_accuracy",
    "behavior_cloning_loss",
    "build_native_replay_corpus",
    "causal_opponent_row_indices",
    "compile_or_load_native_replay",
    "demonstration_batch",
    "load_native_behavior_policy",
    "load_native_replay_corpus",
    "make_behavior_cloning_trainer",
    "make_native_replay_environment",
    "native_arsenal_ability_binding",
    "native_arsenal_ability_binding_sha256",
    "native_arsenal_ability_slot_contract_sha256",
    "native_arsenal_action_head_readiness",
    "native_arsenal_conditioned_observation_sha256",
    "native_arsenal_conditioned_replay_corpus",
    "native_arsenal_npc_role_ability_binding",
    "native_arsenal_profile_basic_attack_binding",
    "native_arsenal_shared_replay_corpus",
    "native_arsenal_visual_conditioned_observation_sha256",
    "native_arsenal_visual_conditioned_replay_corpus",
    "native_arsenal_visual_shared_replay_corpus",
    "native_behavior_observation_projector",
    "native_behavior_policy_logits",
    "native_npc_demonstrations",
    "native_npc_duel_demonstrations",
    "native_replay_ability_slot_contract_sha256",
    "native_replay_action_head_coverage",
    "native_replay_demonstrations",
    "native_replay_ppo_config",
    "native_replay_sequence",
    "native_replay_tensor_sha256",
    "pack_native_replay_sequence",
    "projected_demonstrations",
    "sample_native_replay_rows",
    "split_native_replay_corpus",
    "transplant_native_behavior_policy",
    "write_native_replay_corpus",
]
