"""Staged progression over registered games."""

from arena.curriculum.ladder import Ladder, LadderState, Stage, ladder_for
from arena.curriculum.strategy import (
    AIM_OBJECTIVE,
    ARENA_TRAINING_STRATEGY_SCHEMA,
    ATTACK_TIMING_OBJECTIVE,
    ArenaTrainingStrategy,
    CausalObjective,
    EpisodeContract,
    GUARD_TIMING_OBJECTIVE,
    MINIMUM_SKILL_EPISODE_TICKS,
    PURSUIT_OBJECTIVE,
    SkillAxis,
    TargetMotionContract,
    TargetMotionPattern,
    aim_training_strategy,
    attack_timing_training_strategy,
    compose_training_strategies,
    guard_timing_training_strategy,
    moving_target_motion,
    pursuit_training_strategy,
    radial_strafe_target_motion,
    radial_target_motion,
    stationary_target_motion,
    strafe_target_motion,
)

__all__ = [
    "AIM_OBJECTIVE",
    "ARENA_TRAINING_STRATEGY_SCHEMA",
    "ATTACK_TIMING_OBJECTIVE",
    "ArenaTrainingStrategy",
    "CausalObjective",
    "EpisodeContract",
    "GUARD_TIMING_OBJECTIVE",
    "Ladder",
    "LadderState",
    "MINIMUM_SKILL_EPISODE_TICKS",
    "PURSUIT_OBJECTIVE",
    "SkillAxis",
    "Stage",
    "TargetMotionContract",
    "TargetMotionPattern",
    "aim_training_strategy",
    "attack_timing_training_strategy",
    "compose_training_strategies",
    "guard_timing_training_strategy",
    "ladder_for",
    "moving_target_motion",
    "pursuit_training_strategy",
    "radial_strafe_target_motion",
    "radial_target_motion",
    "stationary_target_motion",
    "strafe_target_motion",
]
