"""Versioned native-derived mechanics rulesets shared with the Java bridge."""

from hytalegym.rulesets.asset_surface import (
    ASSET_SURFACE_AUDIT_RESOURCE,
    ASSET_SURFACE_AUDIT_SCHEMA,
    ASSET_SURFACE_SCAN_PREFIXES,
    AssetSurfaceOccurrence,
    AssetSurfaceReport,
    HYTALE_ASSETS_ZIP_ENV,
    audit_hytale_0_5_7_asset_surface,
    build_asset_surface_report,
    default_hytale_assets_archive,
    load_asset_surface_manifest,
    require_hytale_0_5_7_assets_archive,
)
from hytalegym.rulesets.loader import (
    COMBAT_RULESET_RESOURCE,
    combat_ruleset_sha256,
    load_combat_ruleset,
)
from hytalegym.rulesets.resistances import (
    DamageResistanceProfile,
    combine_damage_resistance_profiles,
    compile_damage_resistance_profile,
    empty_damage_resistance_profile,
)
from hytalegym.rulesets.role_statuses import (
    ROLE_INITIAL_STATUSES_RESOURCE,
    ROLE_INITIAL_STATUSES_SCHEMA,
    ROLE_INITIAL_STATUSES_VERSION,
    RoleInitialStatus,
    load_role_initial_statuses,
    role_initial_statuses_sha256,
)
from hytalegym.rulesets.native_status_projection import (
    NATIVE_STATUS_PROJECTION_DODGE_INVULNERABILITY,
    NATIVE_STATUS_PROJECTION_OMIT_DERIVED_MECHANIC,
    NATIVE_STATUS_PROJECTION_OMIT_VISUAL_ONLY,
    NATIVE_STATUS_PROJECTION_RESOURCE,
    NATIVE_STATUS_PROJECTION_SCHEMA,
    NATIVE_STATUS_PROJECTION_STAMINA_BREAK_IMMUNITY,
    NATIVE_STATUS_PROJECTION_VERSION,
    NativeStatusProjection,
    load_native_status_projections,
    native_status_projection_sha256,
)
from hytalegym.rulesets.movement_projection import (
    ACTOR_WALK_MOVEMENT_PROJECTION_RESOURCE,
    ACTOR_WALK_MOVEMENT_PROJECTION_SCHEMA,
    ACTOR_WALK_MOVEMENT_PROJECTION_VERSION,
    ActorWalkMovementProjection,
    actor_walk_movement_projection_sha256,
    load_actor_walk_movement_projection,
)
from hytalegym.rulesets.damage_causes import (
    DAMAGE_CAUSE_RULESET_RESOURCE,
    DAMAGE_CAUSE_RULESET_SCHEMA,
    DamageCauseRule,
    audit_hytale_0_5_7_damage_causes,
    damage_cause_rules_sha256,
    load_damage_cause_rules,
)
from hytalegym.rulesets.damage_classes import (
    DAMAGE_CLASS_IDS,
    DamageClassEnhancementProfile,
    combine_damage_class_enhancement_profiles,
    compile_damage_class_enhancement_profile,
    damage_class_index,
    empty_damage_class_enhancement_profile,
)

__all__ = [
    "ASSET_SURFACE_AUDIT_RESOURCE",
    "ASSET_SURFACE_AUDIT_SCHEMA",
    "ASSET_SURFACE_SCAN_PREFIXES",
    "ACTOR_WALK_MOVEMENT_PROJECTION_RESOURCE",
    "ACTOR_WALK_MOVEMENT_PROJECTION_SCHEMA",
    "ACTOR_WALK_MOVEMENT_PROJECTION_VERSION",
    "ActorWalkMovementProjection",
    "AssetSurfaceOccurrence",
    "AssetSurfaceReport",
    "COMBAT_RULESET_RESOURCE",
    "DAMAGE_CAUSE_RULESET_RESOURCE",
    "DAMAGE_CAUSE_RULESET_SCHEMA",
    "DAMAGE_CLASS_IDS",
    "DamageCauseRule",
    "DamageClassEnhancementProfile",
    "DamageResistanceProfile",
    "HYTALE_ASSETS_ZIP_ENV",
    "NATIVE_STATUS_PROJECTION_DODGE_INVULNERABILITY",
    "NATIVE_STATUS_PROJECTION_OMIT_DERIVED_MECHANIC",
    "NATIVE_STATUS_PROJECTION_OMIT_VISUAL_ONLY",
    "NATIVE_STATUS_PROJECTION_RESOURCE",
    "NATIVE_STATUS_PROJECTION_SCHEMA",
    "NATIVE_STATUS_PROJECTION_STAMINA_BREAK_IMMUNITY",
    "NATIVE_STATUS_PROJECTION_VERSION",
    "ROLE_INITIAL_STATUSES_RESOURCE",
    "ROLE_INITIAL_STATUSES_SCHEMA",
    "ROLE_INITIAL_STATUSES_VERSION",
    "NativeStatusProjection",
    "RoleInitialStatus",
    "audit_hytale_0_5_7_asset_surface",
    "audit_hytale_0_5_7_damage_causes",
    "actor_walk_movement_projection_sha256",
    "build_asset_surface_report",
    "combine_damage_resistance_profiles",
    "combine_damage_class_enhancement_profiles",
    "combat_ruleset_sha256",
    "compile_damage_resistance_profile",
    "compile_damage_class_enhancement_profile",
    "damage_cause_rules_sha256",
    "damage_class_index",
    "default_hytale_assets_archive",
    "empty_damage_resistance_profile",
    "empty_damage_class_enhancement_profile",
    "load_asset_surface_manifest",
    "load_combat_ruleset",
    "load_damage_cause_rules",
    "load_native_status_projections",
    "load_actor_walk_movement_projection",
    "load_role_initial_statuses",
    "native_status_projection_sha256",
    "role_initial_statuses_sha256",
    "require_hytale_0_5_7_assets_archive",
]
