"""Fixed capacities and failures for logical-entity effect ticking."""

from __future__ import annotations


ENTITY_EFFECTS_SCHEMA = "hytalerl_entity_effect_ticks_v1"
ENTITY_EFFECTS_VERSION = 1

ENTITY_EFFECT_DAMAGE_CAPACITY = 64
ENTITY_EFFECT_MAX_DT_SECONDS = 0.1

ENTITY_EFFECT_CAPABILITY_PERIODIC_DAMAGE = 1 << 0
ENTITY_EFFECT_CAPABILITY_PERIODIC_HEALING = 1 << 1
ENTITY_EFFECT_CAPABILITY_PERIODIC_RESOURCES = 1 << 2
ENTITY_EFFECT_CAPABILITY_SOURCE_GENERATION = 1 << 3
ENTITY_EFFECT_CAPABILITY_NATIVE_DAMAGE_ROUNDING = 1 << 4
ENTITY_EFFECT_CAPABILITIES = (
    ENTITY_EFFECT_CAPABILITY_PERIODIC_DAMAGE
    | ENTITY_EFFECT_CAPABILITY_PERIODIC_HEALING
    | ENTITY_EFFECT_CAPABILITY_PERIODIC_RESOURCES
    | ENTITY_EFFECT_CAPABILITY_SOURCE_GENERATION
    | ENTITY_EFFECT_CAPABILITY_NATIVE_DAMAGE_ROUNDING
)

ENTITY_EFFECT_FAILURE_INVALID_STATE = 1 << 0
ENTITY_EFFECT_FAILURE_INVALID_DT = 1 << 1
ENTITY_EFFECT_FAILURE_UPSTREAM = 1 << 2
ENTITY_EFFECT_FAILURE_STALE_SOURCE = 1 << 3
ENTITY_EFFECT_FAILURE_DAMAGE_OVERFLOW = 1 << 4
ENTITY_EFFECT_FAILURE_MECHANICS = 1 << 5
