"""Pinned combat-profile catalogs."""

from hytalegym.jax.combat.arsenal.profiles.hytale_0_5_7 import (
    NativeInteractionBinding,
    NativeProfileBindings,
    CORE_PROFILE_NAMES,
    CROSSBOW_FAMILY_IDS,
    NATIVE_RESOURCE_STAT_IDS,
    PROFILE_NAMES,
    SHORTBOW_FAMILY_IDS,
    SPEAR_PROFILE_NAMES,
    WORLD_CONDITIONAL_ABILITY_ASSETS,
    ability_loadout_content_sha256,
    hytale_0_5_7_catalog_counts,
    hytale_0_5_7_entity_loadouts,
    hytale_0_5_7_loadouts,
    hytale_0_5_7_native_profile_bindings,
    hytale_0_5_7_program_content_sha256,
    hytale_0_5_7_runtime_capacity,
    native_ability_requested_charge_time_seconds,
    semantic_id,
)
from hytalegym.jax.combat.arsenal.profiles.native_npcs import (
    NATIVE_NPC_ROLE_PROFILE_NAMES,
    NATIVE_NPC_ROLE_PROFILE_SCHEMA,
    hytale_0_5_7_native_npc_role_bindings,
    hytale_0_5_7_native_npc_role_loadouts,
    hytale_0_5_7_native_npc_role_manifest,
    hytale_0_5_7_native_npc_role_program_content_sha256,
)

__all__ = [
    "NativeInteractionBinding",
    "NativeProfileBindings",
    "CORE_PROFILE_NAMES",
    "CROSSBOW_FAMILY_IDS",
    "NATIVE_RESOURCE_STAT_IDS",
    "NATIVE_NPC_ROLE_PROFILE_NAMES",
    "NATIVE_NPC_ROLE_PROFILE_SCHEMA",
    "PROFILE_NAMES",
    "SHORTBOW_FAMILY_IDS",
    "SPEAR_PROFILE_NAMES",
    "WORLD_CONDITIONAL_ABILITY_ASSETS",
    "ability_loadout_content_sha256",
    "hytale_0_5_7_catalog_counts",
    "hytale_0_5_7_entity_loadouts",
    "hytale_0_5_7_loadouts",
    "hytale_0_5_7_native_profile_bindings",
    "hytale_0_5_7_native_npc_role_bindings",
    "hytale_0_5_7_native_npc_role_loadouts",
    "hytale_0_5_7_native_npc_role_manifest",
    "hytale_0_5_7_native_npc_role_program_content_sha256",
    "hytale_0_5_7_program_content_sha256",
    "hytale_0_5_7_runtime_capacity",
    "native_ability_requested_charge_time_seconds",
    "semantic_id",
]
