"""Versioned capability and diagnostic bits for surrogate world queries."""

SURROGATE_CAPABILITY_BLOCK_GEOMETRY = 1 << 0
SURROGATE_CAPABILITY_STATEFUL_BLOCKS = 1 << 1
SURROGATE_CAPABILITY_ENTITY_GEOMETRY = 1 << 2
SURROGATE_CAPABILITY_SWEPT_AABB = 1 << 3
SURROGATE_CAPABILITY_ENTITY_PERCEPTION = 1 << 4

SURROGATE_BASE_CAPABILITIES = (
    SURROGATE_CAPABILITY_BLOCK_GEOMETRY
    | SURROGATE_CAPABILITY_STATEFUL_BLOCKS
    | SURROGATE_CAPABILITY_SWEPT_AABB
)

SURROGATE_FAILURE_WORLD_UNAVAILABLE = 1 << 0
SURROGATE_FAILURE_DOOR_INTENT = 1 << 1
SURROGATE_FAILURE_ENTITY_UPDATE = 1 << 2
SURROGATE_FAILURE_STATE_CHANGE_USE = 1 << 3

SURROGATE_QUERY_INVALID = 1 << 0
SURROGATE_QUERY_COVERAGE = 1 << 1
SURROGATE_QUERY_CAPACITY = 1 << 2
SURROGATE_QUERY_ENTITY_GEOMETRY = 1 << 3
SURROGATE_QUERY_RUNTIME = 1 << 4
SURROGATE_QUERY_ENTITY_LOS_ENDPOINT = 1 << 5

__all__ = [
    "SURROGATE_BASE_CAPABILITIES",
    "SURROGATE_CAPABILITY_BLOCK_GEOMETRY",
    "SURROGATE_CAPABILITY_ENTITY_GEOMETRY",
    "SURROGATE_CAPABILITY_ENTITY_PERCEPTION",
    "SURROGATE_CAPABILITY_STATEFUL_BLOCKS",
    "SURROGATE_CAPABILITY_SWEPT_AABB",
    "SURROGATE_FAILURE_DOOR_INTENT",
    "SURROGATE_FAILURE_ENTITY_UPDATE",
    "SURROGATE_FAILURE_STATE_CHANGE_USE",
    "SURROGATE_FAILURE_WORLD_UNAVAILABLE",
    "SURROGATE_QUERY_CAPACITY",
    "SURROGATE_QUERY_COVERAGE",
    "SURROGATE_QUERY_ENTITY_GEOMETRY",
    "SURROGATE_QUERY_ENTITY_LOS_ENDPOINT",
    "SURROGATE_QUERY_INVALID",
    "SURROGATE_QUERY_RUNTIME",
]
