"""Fixed capacities and failures for 32-entity ability scheduling."""

from __future__ import annotations


ENTITY_ABILITIES_SCHEMA = "hytalerl_entity_abilities_v8"
ENTITY_ABILITIES_VERSION = 8

# Family zero is empty. The pinned Hytale weapon surface contains 233
# non-debug item assets, so keep a byte-sized program key without conflating
# material variants that carry different damage/durability programs.
ABILITY_PROGRAM_FAMILY_CAPACITY = 256
ABILITY_EVENT_CAPACITY = 128
ABILITY_DAMAGE_CAPACITY = 128

ABILITY_CAPABILITY_SCHEDULER = 1 << 0
ABILITY_CAPABILITY_RESOURCES = 1 << 1
ABILITY_CAPABILITY_COOLDOWNS = 1 << 2
ABILITY_CAPABILITY_INTERRUPTION = 1 << 3
ABILITY_CAPABILITY_DIRECT_EVENTS = 1 << 4
ABILITY_CAPABILITY_IMPACT_ROUTING = 1 << 5
ABILITY_CAPABILITY_SOURCE_GENERATION = 1 << 6
ABILITY_CAPABILITY_SEPARATE_WORLD_FAILURE = 1 << 7
ABILITY_CAPABILITIES = (
    ABILITY_CAPABILITY_SCHEDULER
    | ABILITY_CAPABILITY_RESOURCES
    | ABILITY_CAPABILITY_COOLDOWNS
    | ABILITY_CAPABILITY_INTERRUPTION
    | ABILITY_CAPABILITY_DIRECT_EVENTS
    | ABILITY_CAPABILITY_IMPACT_ROUTING
    | ABILITY_CAPABILITY_SOURCE_GENERATION
    | ABILITY_CAPABILITY_SEPARATE_WORLD_FAILURE
)

ABILITY_FAILURE_INVALID_STATE = 1 << 0
ABILITY_FAILURE_INVALID_DT = 1 << 1
ABILITY_FAILURE_INVALID_PROGRAM = 1 << 2
ABILITY_FAILURE_INVALID_COMMAND = 1 << 3
ABILITY_FAILURE_STALE_SOURCE = 1 << 4
ABILITY_FAILURE_AVAILABILITY = 1 << 5
ABILITY_FAILURE_EVENT_OVERFLOW = 1 << 6
ABILITY_FAILURE_UPSTREAM = 1 << 7
ABILITY_FAILURE_QUERY = 1 << 8
ABILITY_FAILURE_STALE_TARGET = 1 << 9
ABILITY_FAILURE_AMBIGUOUS_TARGET = 1 << 10
ABILITY_FAILURE_DAMAGE_OVERFLOW = 1 << 11
ABILITY_FAILURE_STATUS_OVERFLOW = 1 << 12
ABILITY_FAILURE_MECHANICS = 1 << 13
ABILITY_FAILURE_LAUNCH = 1 << 14
