"""Executable skill-stage machinery shared by every lesson.

``program``
    Content-addressed target programs and ``FactoredActionScope``, the
    per-head restriction every contract uses to pin the mechanics it does not
    score.
``signals``
    Pure-JAX causal signals and episode-ending laws, including the
    counterfactual credit used to keep opponent-produced motion out of a
    learner's reward.
``stage``
    Reset and binding contracts for two-actor stages: role assignment, spawn
    geometry, and the collector seams a lesson plugs into.
"""

from __future__ import annotations

from arena.training.skills.program import (
    FACTORED_ACTION_SCOPE_SCHEMA,
    FactoredActionScope,
    TARGET_MOTION_PROGRAM_SCHEMA,
    TargetMode,
    TargetMotionOutput,
    TargetMotionProgram,
    target_motion_factors,
)
from arena.training.skills.signals import (
    AIM_REWARD_LAW,
    AIM_SUCCESS_DEGREES,
    AIM_SUSTAINED_ALIGNMENT_SCHEMA,
    AIM_TRACKING_SIGNAL_SCHEMA,
    ATTACK_INTERVAL_OUTCOME_SCHEMA,
    ATTACK_TIMING_REWARD_LAW,
    AimAlignmentProgressSignals,
    AimTrackingSignals,
    AttackIntervalCarry,
    AttackIntervalOutcomeSignals,
    AttackTimingSignals,
    EpisodeProgressSignals,
    PITCH_TRACKING_SIGNAL_SCHEMA,
    PURSUIT_REWARD_LAW,
    PURSUIT_SUCCESS_DISTANCE,
    PitchTrackingSignals,
    PursuitTransitionSignals,
    SPATIAL_TRACKING_SIGNAL_SCHEMA,
    SpatialTrackingSignals,
    advance_aim_alignment_progress,
    advance_episode_progress,
    aim_sustained_alignment_contract_manifest,
    aim_sustained_alignment_contract_sha256,
    aim_tracking_geometry_signals,
    aim_tracking_signal_contract_manifest,
    aim_tracking_signal_contract_sha256,
    aim_tracking_signals,
    attack_interval_outcome_contract_manifest,
    attack_interval_outcome_contract_sha256,
    attack_interval_outcome_signals,
    attack_timing_signals,
    pitch_tracking_geometry_signals,
    pitch_tracking_signal_contract_manifest,
    pitch_tracking_signal_contract_sha256,
    pitch_tracking_signals,
    pursuit_transition_signals,
    spatial_tracking_geometry_signals,
    spatial_tracking_signal_contract_manifest,
    spatial_tracking_signal_contract_sha256,
    spatial_tracking_signals,
)
from arena.training.skills.stage import (
    ARENA_SKILL_STAGE_ARTIFACT_SCHEMA,
    ARENA_SKILL_STAGE_PROGRAM_SCHEMA,
    ArenaSkillStageProgram,
    BOUND_ARENA_SKILL_STAGE_IDENTITY_SCHEMA,
    BoundArenaSkillStageIdentity,
    HealthResetLaw,
    PairPlacement,
    RADIAL_PAIR_PLACEMENT_SCHEMA,
    RadialPairPlacementProgram,
    SKILL_RESET_PROGRAM_SCHEMA,
    ScriptedTargetActionMask,
    SkillDuelRoles,
    SkillResetOutput,
    SkillResetProgram,
    YawErrorDistribution,
    bind_arena_skill_stage_identity,
    combat_params_content_sha256,
    radial_pair_placement,
    reset_radial_skill_duel,
    reset_skill_duel,
    scripted_target_action_mask,
    skill_duel_roles,
    skill_stage_artifact,
    skill_stage_parameter_mask,
)


__all__ = [
    "AIM_REWARD_LAW",
    "AIM_SUCCESS_DEGREES",
    "AIM_SUSTAINED_ALIGNMENT_SCHEMA",
    "AIM_TRACKING_SIGNAL_SCHEMA",
    "ARENA_SKILL_STAGE_ARTIFACT_SCHEMA",
    "ARENA_SKILL_STAGE_PROGRAM_SCHEMA",
    "ATTACK_INTERVAL_OUTCOME_SCHEMA",
    "ATTACK_TIMING_REWARD_LAW",
    "AimAlignmentProgressSignals",
    "AimTrackingSignals",
    "ArenaSkillStageProgram",
    "AttackIntervalCarry",
    "AttackIntervalOutcomeSignals",
    "AttackTimingSignals",
    "BOUND_ARENA_SKILL_STAGE_IDENTITY_SCHEMA",
    "BoundArenaSkillStageIdentity",
    "EpisodeProgressSignals",
    "FACTORED_ACTION_SCOPE_SCHEMA",
    "FactoredActionScope",
    "HealthResetLaw",
    "PITCH_TRACKING_SIGNAL_SCHEMA",
    "PURSUIT_REWARD_LAW",
    "PURSUIT_SUCCESS_DISTANCE",
    "PairPlacement",
    "PitchTrackingSignals",
    "PursuitTransitionSignals",
    "RADIAL_PAIR_PLACEMENT_SCHEMA",
    "RadialPairPlacementProgram",
    "SKILL_RESET_PROGRAM_SCHEMA",
    "SPATIAL_TRACKING_SIGNAL_SCHEMA",
    "ScriptedTargetActionMask",
    "SkillDuelRoles",
    "SkillResetOutput",
    "SkillResetProgram",
    "SpatialTrackingSignals",
    "TARGET_MOTION_PROGRAM_SCHEMA",
    "TargetMode",
    "TargetMotionOutput",
    "TargetMotionProgram",
    "YawErrorDistribution",
    "advance_aim_alignment_progress",
    "advance_episode_progress",
    "aim_sustained_alignment_contract_manifest",
    "aim_sustained_alignment_contract_sha256",
    "aim_tracking_geometry_signals",
    "aim_tracking_signal_contract_manifest",
    "aim_tracking_signal_contract_sha256",
    "aim_tracking_signals",
    "attack_interval_outcome_contract_manifest",
    "attack_interval_outcome_contract_sha256",
    "attack_interval_outcome_signals",
    "attack_timing_signals",
    "bind_arena_skill_stage_identity",
    "combat_params_content_sha256",
    "pitch_tracking_geometry_signals",
    "pitch_tracking_signal_contract_manifest",
    "pitch_tracking_signal_contract_sha256",
    "pitch_tracking_signals",
    "pursuit_transition_signals",
    "radial_pair_placement",
    "reset_radial_skill_duel",
    "reset_skill_duel",
    "scripted_target_action_mask",
    "skill_duel_roles",
    "skill_stage_artifact",
    "skill_stage_parameter_mask",
    "spatial_tracking_geometry_signals",
    "spatial_tracking_signal_contract_manifest",
    "spatial_tracking_signal_contract_sha256",
    "spatial_tracking_signals",
    "target_motion_factors",
]
