"""Private HytaleRL Agent Development Kit."""

import importlib

from adk import _runtime_environment as _runtime_environment


#: Pre-1.0: the public surface is stable in practice but not yet frozen.
#:
#: ``adk/tests/test_public_surface.py`` pins the names an agent author is
#: expected to build against, so a removal or rename is a deliberate act rather
#: than an accident.  Bump this when that pinned set changes incompatibly.
__version__ = "0.1.0"

from adk.architecture import (
    ActorDecision,
    ActionLifecycle,
    ActionVerb,
    ActorObservationCompiler,
    ActorObservationEnvelope,
    ActorPolicyInput,
    AgentArchitecture,
    AuthoritativeSnapshot,
    BeliefCore,
    BeliefUpdate,
    CompatibilityError,
    ComponentBinding,
    ComponentRegistry,
    ContentDigest,
    DecisionTransition,
    DecisionContext,
    DecisionContextFrame,
    DecisionEvent,
    DecisionEvents,
    DecisionTiming,
    ExperienceSource,
    ExecutionState,
    GoalControl,
    GoalDecision,
    GoalRuntimeContext,
    HierarchicalAgentCore,
    HierarchicalCarry,
    HierarchicalCoreState,
    HierarchicalStep,
    HytaleBackend,
    InferenceMetadata,
    InferenceValidation,
    InferenceValidationContext,
    JaxTrainingInput,
    LowLevelActor,
    ManagedGoal,
    OptionTransition,
    PLAN_COMPONENT_ROLES,
    PrivilegedCritic,
    PrivilegedSceneCompiler,
    PrivilegedSceneEnvelope,
    PrivilegedTeacher,
    ProviderContract,
    RuntimeIdentity,
    SchemaBundle,
    SchemaRef,
    SequenceReplaySpec,
    ShortHorizonWorldModel,
    SnapshotHeader,
    StaleInferenceReason,
    TacticalManager,
    TickRecord,
    ValuePrediction,
    WorldModelPrediction,
    action_mask_hash,
    bind_component,
    compose_architecture,
    compose_provider_contracts,
    capture_inference_metadata,
    jax_decision_context,
    initialize_hierarchical_state,
    manager_decision_due,
    native_decision_context,
    validate_inference_result,
)
from adk.api import (
    ActionHead,
    ActionIntent,
    ActionSpace,
    AgentFrame,
    AgentHandle,
    AgentKit,
    AgentSpec,
    BaseAction,
    BlockTrigger,
    BridgePolicyInput,
    BridgeTransition,
    BuiltAgent,
    COMBAT_PARAMETER_NAMES,
    CompositeActionHead,
    CompositeActionSpec,
    ContextualLoopState,
    ContextualLoopTransition,
    ContextualPolicy,
    ContextualPolicyInput,
    ContextualRecordFn,
    DensePolicySurface,
    DodgeDirection,
    EnvironmentDiagnostics,
    EnvironmentActionBoundary,
    EnvironmentActionReceipt,
    EnvironmentStep,
    EpisodeBoundary,
    ENVIRONMENT_STATE_SELECTOR_SCHEMA,
    FAIL_CLOSED_SCENE,
    HYTALE_ENV_PARAMETER_BINDINGS,
    HytaleEnv,
    HierarchicalActorInputFn,
    HierarchicalContextFn,
    HierarchicalLoopState,
    HierarchicalLoopTransition,
    HierarchicalRecordFn,
    HierarchicalRuntimeDiagnostics,
    JAX_SCENE_PROVIDER_ARGUMENTS,
    JaxBuildInputs,
    JaxRuntimeSettings,
    JaxScene,
    JointActionCapability,
    JointActionRejected,
    JointExecutionFailed,
    JointExecutionUnavailable,
    JointValidationUnavailable,
    LoopState,
    LoopTransition,
    MaskedCompositeSample,
    NativeBridgeSession,
    OPEN_FLAT_CONTROL_SCENE,
    Policy,
    PolicyInput,
    RUNTIME_CONFIG_ARGUMENTS,
    RecordFn,
    SceneDescription,
    StepResult,
    StructuredActionCodec,
    Trajectory,
    WorldDirection,
    build,
    collect_contextual,
    collect_hierarchical,
    compile_hierarchical_collector,
    configure_jax_compilation_cache,
    default_kit,
    describe_scene,
    jax_hierarchical_context,
    list_loadouts,
    make_scene,
    prepare_jax_build_inputs,
    scene_from_region_fixture,
    describe_spawns,
    fixed_spawns,
    lit_surface_spawns,
    region_pool_spawns,
    select_environment_rows,
    shifted,
    swapped,
    unknown_decision_context,
)
from adk.policy.random_policy import uniform_legal


_LAZY_EXPORTS = {
    "EvaluationResult": ("adk.api", "EvaluationResult"),
    "EvaluationSuite": ("adk.api", "EvaluationSuite"),
    "LoadedCheckpoint": ("adk.api", "LoadedCheckpoint"),
    "PPOConfig": ("adk.api", "PPOConfig"),
    "PPOEnvironment": ("adk.api", "PPOEnvironment"),
    "PPOTrainState": ("adk.api", "PPOTrainState"),
}


def __getattr__(name: str):
    """Resolve optional training/lifecycle exports only on explicit access."""

    try:
        module_name, attribute_name = _LAZY_EXPORTS[name]
    except KeyError as error:
        raise AttributeError(
            f"module {__name__!r} has no attribute {name!r}"
        ) from error
    value = getattr(importlib.import_module(module_name), attribute_name)
    globals()[name] = value
    return value


__all__ = [
    "ActorDecision",
    "ActionHead",
    "ActionIntent",
    "ActionLifecycle",
    "ActionSpace",
    "ActionVerb",
    "AgentFrame",
    "AgentHandle",
    "AgentKit",
    "AgentSpec",
    "ActorObservationCompiler",
    "ActorObservationEnvelope",
    "ActorPolicyInput",
    "AgentArchitecture",
    "AuthoritativeSnapshot",
    "BaseAction",
    "BeliefCore",
    "BeliefUpdate",
    "BlockTrigger",
    "BridgePolicyInput",
    "BridgeTransition",
    "BuiltAgent",
    "COMBAT_PARAMETER_NAMES",
    "CompositeActionHead",
    "CompositeActionSpec",
    "ContextualLoopState",
    "ContextualLoopTransition",
    "ContextualPolicy",
    "ContextualPolicyInput",
    "ContextualRecordFn",
    "DensePolicySurface",
    "CompatibilityError",
    "ComponentBinding",
    "ComponentRegistry",
    "ContentDigest",
    "DecisionTransition",
    "DecisionContext",
    "DecisionContextFrame",
    "DecisionEvent",
    "DecisionEvents",
    "DecisionTiming",
    "DodgeDirection",
    "EnvironmentDiagnostics",
    "EnvironmentActionBoundary",
    "EnvironmentActionReceipt",
    "EnvironmentStep",
    "EpisodeBoundary",
    "EvaluationResult",
    "EvaluationSuite",
    "ExperienceSource",
    "ExecutionState",
    "ENVIRONMENT_STATE_SELECTOR_SCHEMA",
    "FAIL_CLOSED_SCENE",
    "HYTALE_ENV_PARAMETER_BINDINGS",
    "HytaleEnv",
    "HytaleBackend",
    "HierarchicalActorInputFn",
    "HierarchicalContextFn",
    "InferenceMetadata",
    "InferenceValidation",
    "InferenceValidationContext",
    "GoalControl",
    "GoalDecision",
    "GoalRuntimeContext",
    "HierarchicalAgentCore",
    "HierarchicalCarry",
    "HierarchicalCoreState",
    "HierarchicalStep",
    "HierarchicalLoopState",
    "HierarchicalLoopTransition",
    "HierarchicalRecordFn",
    "HierarchicalRuntimeDiagnostics",
    "JAX_SCENE_PROVIDER_ARGUMENTS",
    "JaxBuildInputs",
    "JaxRuntimeSettings",
    "JaxScene",
    "JaxTrainingInput",
    "JointActionCapability",
    "JointActionRejected",
    "JointExecutionFailed",
    "JointExecutionUnavailable",
    "JointValidationUnavailable",
    "LoadedCheckpoint",
    "LoopState",
    "LoopTransition",
    "LowLevelActor",
    "ManagedGoal",
    "MaskedCompositeSample",
    "NativeBridgeSession",
    "OPEN_FLAT_CONTROL_SCENE",
    "OptionTransition",
    "PLAN_COMPONENT_ROLES",
    "PPOConfig",
    "PPOEnvironment",
    "PPOTrainState",
    "Policy",
    "PolicyInput",
    "RecordFn",
    "PrivilegedCritic",
    "PrivilegedSceneCompiler",
    "PrivilegedSceneEnvelope",
    "PrivilegedTeacher",
    "ProviderContract",
    "RUNTIME_CONFIG_ARGUMENTS",
    "RuntimeIdentity",
    "SceneDescription",
    "SchemaBundle",
    "SchemaRef",
    "SequenceReplaySpec",
    "ShortHorizonWorldModel",
    "SnapshotHeader",
    "StepResult",
    "StructuredActionCodec",
    "StaleInferenceReason",
    "Trajectory",
    "TacticalManager",
    "TickRecord",
    "ValuePrediction",
    "WorldDirection",
    "WorldModelPrediction",
    "action_mask_hash",
    "bind_component",
    "build",
    "collect_contextual",
    "collect_hierarchical",
    "compile_hierarchical_collector",
    "compose_architecture",
    "compose_provider_contracts",
    "capture_inference_metadata",
    "configure_jax_compilation_cache",
    "default_kit",
    "describe_scene",
    "jax_decision_context",
    "jax_hierarchical_context",
    "list_loadouts",
    "make_scene",
    "initialize_hierarchical_state",
    "manager_decision_due",
    "native_decision_context",
    "prepare_jax_build_inputs",
    "scene_from_region_fixture",
    "describe_spawns",
    "fixed_spawns",
    "lit_surface_spawns",
    "region_pool_spawns",
    "select_environment_rows",
    "shifted",
    "swapped",
    "unknown_decision_context",
    "uniform_legal",
    "validate_inference_result",
]
