"""Generate `adk/docs/CATALOG.md` from live data. Never hand-edit that file.

A hand-written list of weapons goes stale the first time the bank changes, and
a stale catalog is worse than none -- it reads authoritative. Everything here is
read from the authored profile bank and the region library at generation time,
and the output stamps what it was generated from.

    python -m adk.tools.catalog
"""

from __future__ import annotations

import json
from datetime import datetime, timezone
from pathlib import Path

import numpy as np

ROOT = Path(__file__).resolve().parents[2]
DOCS = ROOT / "adk" / "docs"
REGIONS = ROOT / "HytaleRL" / "artifacts" / "worldgen" / "region-library-pilot-v2"


def weapon_rows():
    from hytalegym.jax.combat.arsenal.profiles.hytale_0_5_7 import (
        PROFILE_NAMES, hytale_0_5_7_loadouts)
    from hytalegym.jax.combat.types import AGENT_ENTITY
    import hytalegym.jax.combat.mechanics as mechanics

    resources = {int(getattr(mechanics, n)): n.replace("RESOURCE_", "").lower()
                 for n in dir(mechanics)
                 if n.startswith("RESOURCE_") and n != "RESOURCE_COUNT"}
    stamina = next(i for i, n in resources.items() if n == "stamina")
    ammo = next(i for i, n in resources.items() if n == "ammo")

    names = list(PROFILE_NAMES)
    bank = hytale_0_5_7_loadouts(names, target_profiles=names)
    A = AGENT_ENTITY
    mask = np.asarray(bank.ability_mask)[:, A]
    cost = np.asarray(bank.ability_resource_cost)[:, A]
    charges = np.asarray(bank.ability_charge_capacity)[:, A]
    cooldown = np.asarray(bank.ability_cooldown_seconds)[:, A]
    guard = np.asarray(bank.guard_stamina_value)[:, A]

    rows = []
    for index, name in enumerate(names):
        live = mask[index]
        count = int(live.sum())
        rows.append({
            "name": name,
            "abilities": count,
            "guard": float(guard[index]),
            "stamina": float(cost[index][live][:, stamina].sum()) if count else 0.0,
            "ammo": float(cost[index][live][:, ammo].sum()) if count else 0.0,
            "charges": int(charges[index][live].max()) if count else 0,
            "cooldown": float(cooldown[index][live].max()) if count else 0.0,
        })
    return rows, resources


def region_rows():
    manifest = json.loads((REGIONS / "manifest.json").read_text())
    diversity = json.loads((REGIONS / "diversity.json").read_text())
    return manifest, diversity


def main() -> int:
    rows, resources = weapon_rows()
    manifest, diversity = region_rows()
    DOCS.mkdir(parents=True, exist_ok=True)

    guarding = [r for r in rows if r["guard"] > 0]
    ranged = [r for r in rows if r["ammo"] > 0]
    charged = [r for r in rows if r["charges"] > 1]
    costly = [r for r in rows if r["stamina"] > 0]

    out = [
        "# Catalog — weapons, terrains, and scene options",
        "",
        "**Generated by `python -m adk.tools.catalog`. Do not hand-edit.**",
        f"Generated {datetime.now(timezone.utc).isoformat(timespec='seconds')} "
        f"from the authored profile bank and "
        f"`region-library-pilot-v2` "
        f"(`{manifest['library_semantic_sha256'][:16]}`).",
        "",
        "## Resources",
        "",
        "| index | name |",
        "|---:|---|",
        *(f"| {i} | `{n}` |" for i, n in sorted(resources.items())),
        "",
        "Stamina max 10, signature_energy max 20, oxygen max 100; the rest are "
        "weapon-supplied. Read a resource with "
        "`minigames.framework.resource(index)`.",
        "",
        "## Weapons",
        "",
        f"**{len(rows)} profiles. Every one has at least one ability** "
        f"({min(r['abilities'] for r in rows)}–"
        f"{max(r['abilities'] for r in rows)}).",
        "",
        f"- **{len(guarding)}** can guard (`guard_stamina_value > 0`). "
        "The other "
        f"{len(rows) - len(guarding)} cannot, and the `block` minigame is "
        "meaningless on them.",
        f"- **{len(ranged)}** consume ammo — usable with an ammo-discipline "
        "objective.",
        f"- **{len(charged)}** have multi-charge abilities.",
        f"- **{len(costly)}** have at least one ability that costs stamina.",
        "",
        "Full table, sorted by ability count:",
        "",
        "| profile | abilities | guard | stamina cost | ammo | charges | max cd |",
        "|---|---:|---:|---:|---:|---:|---:|",
    ]
    for row in sorted(rows, key=lambda r: (-r["abilities"], r["name"])):
        out.append(
            f"| `{row['name']}` | {row['abilities']} | {row['guard']:.1f} | "
            f"{row['stamina']:.2f} | {row['ammo']:.0f} | {row['charges']} | "
            f"{row['cooldown']:.2f} |")

    entries = manifest["entries"]
    train = [e for e in entries if e["split"] == "train"]
    held = [e for e in entries if e["split"] == "heldout"]
    out += [
        "",
        "## Terrain",
        "",
        f"**{manifest['artifact_count']} captured regions** — "
        f"{len(train)} train, {len(held)} heldout. "
        f"Authority `{manifest['authority']}`, "
        f"source `{manifest['runtime_source']}`.",
        "",
        "Measured geometry is near-identical across all of them: solid 32–38%, "
        "water 0.2–0.6%, lava 0%, no cave enclosure. `diversity.json` agrees — "
        "heldout-to-train nearest-neighbour ratio "
        f"**{diversity['geometric_coverage_proxy']['heldout_to_train_median_ratio']:.2f}**. "
        "That is faithful: Hytale spawns you in the same kind of environment. "
        "It does mean held-out *terrain* generalization cannot be measured here, "
        "and the library says so itself: `policy_generalization: "
        f"\"{diversity['policy_generalization']['status']}\"`.",
        "",
        "**Batch does not vary terrain.** All rows of a batch are byte-identical "
        "(0 of 8271 observation columns differ). Vary `node_seed` instead — "
        "three seeds gave 3/3 distinct spawns and 1493–1530 differing columns.",
        "",
        "| seed | split |",
        "|---|---|",
        *(f"| `{e['seed']}` | {e['split']} |" for e in entries),
        "",
        "## Worlds (capability providers)",
        "",
        "| `world=` | ability head | dodge head | attack possible |",
        "|---|---|---|---|",
        "| `open_flat` | {0,1,2,3,4} | {0,3,4} | yes |",
        "| `fail_closed` | **{0}** | **{0}** | **no** |",
        "| `region` | {0,1,2,3,4} | {0,3,4} | yes |",
        "",
        "`fail_closed` is what you get when no provider is passed. It denies "
        "line of sight, target selection, projectile flight and dodge corridor, "
        "so **nothing offensive is learnable under it**. `open_flat` is what the "
        "Gym's own training-readiness gates use. `region` gives the same combat "
        "surface on real geometry.",
        "",
        "`base_action` attack indices {6,7,8} are never legal on any provider — "
        "by design. Attacks go through the ability head.",
        "",
        "## Opponent",
        "",
        "The ruleset holds the opponent at "
        "`target.maintain_distance.desired_distance_min/_max = 2.8`, which suits "
        "the legacy Trork battleaxe (authored reach 0.1→3.0, 23.0 damage). An "
        "arsenal opponent attacks through abilities, whose melee damage peaks "
        "near 0.83 — so at 2.8 it parks outside its own reach. Measured over 250 "
        "ticks × batch 4 with the agent idle:",
        "",
        "| `opponent_distance` | damage to agent | agent deaths |",
        "|---:|---:|---:|",
        "| 2.8 (ruleset default) | 50.0 | 0 |",
        "| 2.0 | 420.0 | 4/4 |",
        "| 1.5 | 420.0 | 4/4 |",
        "| 1.2 | 420.0 | 4/4 |",
        "| 0.9 | 420.0 | 4/4 |",
        "| 0.6 | 420.0 | 4/4 |",
        "",
        "`SceneConfig.opponent_distance` defaults to **2.0** for this reason.",
        "",
    ]
    path = DOCS / "CATALOG.md"
    path.write_text("\n".join(out) + "\n", encoding="utf-8")
    print(f"wrote {path}")
    print(f"  {len(rows)} weapons, {len(entries)} regions, "
          f"{len(resources)} resources")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
