"""30 TPS engine boundaries retained by data-driven ability programs."""

from __future__ import annotations


NATIVE_TICKS_PER_SECOND = 30

# Common_StatAmmoReload_Entry begins with Simple.RunTime=0.8. Each Repeat
# child then runs Common_StatAmmoReload_Effects for 0.3 s, but RepeatInteraction
# needs one additional engine tick to observe the fork and start its next
# child. The failed StatsCondition tail runs Common_Bow_No_Ammo for 0.25 s.
# Durations round up at their discrete 30 TPS boundaries.
CROSSBOW_RELOAD_STARTUP_TICKS = 24
CROSSBOW_RELOAD_EFFECT_TICKS = 9
CROSSBOW_RELOAD_REPEAT_FORK_TICKS = 1
CROSSBOW_RELOAD_REPEAT_TICKS = (
    CROSSBOW_RELOAD_EFFECT_TICKS + CROSSBOW_RELOAD_REPEAT_FORK_TICKS
)
CROSSBOW_RELOAD_FAILED_TAIL_TICKS = 8
CROSSBOW_RELOAD_REPEAT_COUNT = 6

CROSSBOW_RELOAD_STARTUP_SECONDS = (
    CROSSBOW_RELOAD_STARTUP_TICKS / NATIVE_TICKS_PER_SECOND
)
CROSSBOW_RELOAD_REPEAT_SECONDS = (
    CROSSBOW_RELOAD_REPEAT_TICKS / NATIVE_TICKS_PER_SECOND
)
CROSSBOW_RELOAD_FAILED_TAIL_SECONDS = 0.25
CROSSBOW_RELOAD_DURATION_SECONDS = (
    CROSSBOW_RELOAD_STARTUP_TICKS
    + CROSSBOW_RELOAD_REPEAT_COUNT * CROSSBOW_RELOAD_REPEAT_TICKS
    + CROSSBOW_RELOAD_FAILED_TAIL_TICKS
) / NATIVE_TICKS_PER_SECOND
CROSSBOW_RELOAD_RESOURCE_TIMES_SECONDS = tuple(
    (
        CROSSBOW_RELOAD_STARTUP_TICKS
        + (repeat + 1) * CROSSBOW_RELOAD_REPEAT_TICKS
    )
    / NATIVE_TICKS_PER_SECOND
    for repeat in range(CROSSBOW_RELOAD_REPEAT_COUNT)
)


__all__ = [
    "CROSSBOW_RELOAD_DURATION_SECONDS",
    "CROSSBOW_RELOAD_FAILED_TAIL_SECONDS",
    "CROSSBOW_RELOAD_FAILED_TAIL_TICKS",
    "CROSSBOW_RELOAD_REPEAT_COUNT",
    "CROSSBOW_RELOAD_REPEAT_FORK_TICKS",
    "CROSSBOW_RELOAD_REPEAT_SECONDS",
    "CROSSBOW_RELOAD_REPEAT_TICKS",
    "CROSSBOW_RELOAD_RESOURCE_TIMES_SECONDS",
    "CROSSBOW_RELOAD_STARTUP_SECONDS",
    "CROSSBOW_RELOAD_STARTUP_TICKS",
    "NATIVE_TICKS_PER_SECOND",
]
