"""Host-only records for compact special weapon graphs."""

from .hytale_0_5_7 import (
    DOUBLE_INCANDESCENT_SPEAR_ASSET_ID,
    DOUBLE_INCANDESCENT_SPEAR_FAMILY_ID,
    DOUBLE_INCANDESCENT_SPEAR_PROFILE_NAME,
    KNIFE_WEAPON_PROFILE_NAMES,
    KNIFE_WEAPON_VARIANTS,
    SPECIAL_WEAPON_PROFILE_NAMES,
    TRIBAL_BLOWGUN_ASSET_ID,
    TRIBAL_BLOWGUN_FAMILY_ID,
    TRIBAL_BLOWGUN_PROFILE_NAME,
    TRIBAL_CLAWS_ASSET_ID,
    TRIBAL_CLAWS_FAMILY_ID,
    TRIBAL_CLAWS_PROFILE_NAME,
    KnifeWeaponVariant,
)
from .guns import GUN_PROFILE_NAMES, GUN_SPECS, GunSpec
from .prototype_bows import (
    PROTOTYPE_BOW_PROFILE_NAMES,
    PROTOTYPE_BOW_SPECS,
    PrototypeBowSpec,
)

__all__ = [
    "DOUBLE_INCANDESCENT_SPEAR_ASSET_ID",
    "DOUBLE_INCANDESCENT_SPEAR_FAMILY_ID",
    "DOUBLE_INCANDESCENT_SPEAR_PROFILE_NAME",
    "KNIFE_WEAPON_PROFILE_NAMES",
    "KNIFE_WEAPON_VARIANTS",
    "KnifeWeaponVariant",
    "GUN_PROFILE_NAMES",
    "GUN_SPECS",
    "GunSpec",
    "PROTOTYPE_BOW_PROFILE_NAMES",
    "PROTOTYPE_BOW_SPECS",
    "PrototypeBowSpec",
    "SPECIAL_WEAPON_PROFILE_NAMES",
    "TRIBAL_BLOWGUN_ASSET_ID",
    "TRIBAL_BLOWGUN_FAMILY_ID",
    "TRIBAL_BLOWGUN_PROFILE_NAME",
    "TRIBAL_CLAWS_ASSET_ID",
    "TRIBAL_CLAWS_FAMILY_ID",
    "TRIBAL_CLAWS_PROFILE_NAME",
]
