"""Versioned fixed-capacity combat-effect constants."""

from __future__ import annotations

from hytalegym.jax.combat.observation.v1.schema.contract import (
    HAZARD_CAPACITY,
    PROJECTILE_CAPACITY,
)
from hytalegym.worldgen.region.stability import (
    current_native_evidence_jar_sha256,
)


COMBAT_EFFECTS_SCHEMA = "hytalerl_combat_effects_v1"
COMBAT_EFFECTS_VERSION = 1

PROJECTILE_KIND_NONE = 0
PROJECTILE_KIND_OUTLANDER_HUNTER_ARROW = 1
HAZARD_KIND_NONE = 0
HAZARD_KIND_AABB_DAMAGE = 1

PROJECTILE_FLAG_IMPACTED = 1 << 0

EFFECT_FAILURE_PROJECTILE_OVERFLOW = 1 << 0
EFFECT_FAILURE_HAZARD_OVERFLOW = 1 << 1
EFFECT_FAILURE_UNSUPPORTED_COLLISION = 1 << 2
EFFECT_FAILURE_INVALID_COMMAND = 1 << 3
EFFECT_FAILURE_INVALID_STATE = 1 << 4

HYTALE_0_5_7_ASSETS_SHA256 = (
    "1B8802C284C228AE4549DAC037716C175BC6B94B0FC9AAC2B7039AC6BD2FFD5D"
)
HYTALE_0_5_7_NATIVE_EVIDENCE_JAR_SHA256 = (
    current_native_evidence_jar_sha256()
)
OUTLANDER_ARROW_ASSET_SHA256 = (
    "583B1A910B0C99BC94A079E9FAF3C15969C7A225D96CA8A7FFF8FF22E86C35B2"
)
OUTLANDER_ARROW_MODEL_HALF_EXTENT = 0.075
OUTLANDER_ARROW_MUZZLE_VELOCITY = 50.0
OUTLANDER_ARROW_TERMINAL_VELOCITY = 50.0
OUTLANDER_ARROW_GRAVITY = 10.0
OUTLANDER_ARROW_DAMAGE = 15.0
OUTLANDER_ARROW_DEAD_TIME_SECONDS = 0.1
OUTLANDER_ARROW_AUTHORED_LIFETIME_SECONDS = 20.0
OUTLANDER_ARROW_SERVER_DESPAWN_SECONDS = 60.0
OUTLANDER_ARROW_DEPTH_OFFSET = 0.8
OUTLANDER_ARROW_VERTICAL_OFFSET = 0.3

__all__ = [
    "COMBAT_EFFECTS_SCHEMA",
    "COMBAT_EFFECTS_VERSION",
    "EFFECT_FAILURE_HAZARD_OVERFLOW",
    "EFFECT_FAILURE_INVALID_COMMAND",
    "EFFECT_FAILURE_INVALID_STATE",
    "EFFECT_FAILURE_PROJECTILE_OVERFLOW",
    "EFFECT_FAILURE_UNSUPPORTED_COLLISION",
    "HAZARD_CAPACITY",
    "HAZARD_KIND_AABB_DAMAGE",
    "HAZARD_KIND_NONE",
    "HYTALE_0_5_7_ASSETS_SHA256",
    "HYTALE_0_5_7_NATIVE_EVIDENCE_JAR_SHA256",
    "OUTLANDER_ARROW_ASSET_SHA256",
    "OUTLANDER_ARROW_AUTHORED_LIFETIME_SECONDS",
    "OUTLANDER_ARROW_DAMAGE",
    "OUTLANDER_ARROW_DEAD_TIME_SECONDS",
    "OUTLANDER_ARROW_DEPTH_OFFSET",
    "OUTLANDER_ARROW_GRAVITY",
    "OUTLANDER_ARROW_MODEL_HALF_EXTENT",
    "OUTLANDER_ARROW_MUZZLE_VELOCITY",
    "OUTLANDER_ARROW_SERVER_DESPAWN_SECONDS",
    "OUTLANDER_ARROW_TERMINAL_VELOCITY",
    "OUTLANDER_ARROW_VERTICAL_OFFSET",
    "PROJECTILE_CAPACITY",
    "PROJECTILE_FLAG_IMPACTED",
    "PROJECTILE_KIND_NONE",
    "PROJECTILE_KIND_OUTLANDER_HUNTER_ARROW",
]
