"""Fixed ranged-controller IDs and Hytale 0.5.7 timing constants."""

CONTROLLER_SCHEMA = "hytalerl_ranged_controllers_v1"
CONTROLLER_VERSION = 1

PHASE_IDLE = 0
PHASE_SHORTBOW_NOCK = 1
PHASE_SHORTBOW_CHARGE = 2
PHASE_SHORTBOW_VOLLEY_CHARGE = 3
PHASE_CROSSBOW_RELOAD_ENTRY = 4
PHASE_CROSSBOW_RELOAD_LOOP = 5
PHASE_COUNT = 6

ACTION_PRIMARY = 0
ACTION_SIGNATURE = 1
ACTION_RELOAD = 2
ACTION_SWAP = 3
ACTION_COUNT = 4

CONTROLLER_FAILURE_INVALID_STATE = 1 << 0
CONTROLLER_FAILURE_INVALID_COMMAND = 1 << 1
CONTROLLER_FAILURE_INVALID_DT = 1 << 2
CONTROLLER_FAILURE_UNCERTIFIED_INTERRUPT = 1 << 3

SHORTBOW_NOCK_SECONDS = 0.1
SHORTBOW_CHARGE_THRESHOLDS = (0.1, 0.3, 0.6, 0.9, 1.2)
SHORTBOW_VOLLEY_THRESHOLDS = (0.0, 0.75, 1.5)
SHORTBOW_CHARGE_SPEED_MULTIPLIER = 0.667

CROSSBOW_PRIMARY_COOLDOWN_SECONDS = 0.3
CROSSBOW_RELOAD_ENTRY_SECONDS = 0.8
CROSSBOW_RELOAD_ARROW_SECONDS = 0.3
CROSSBOW_RELOAD_SPEED_MULTIPLIER = 0.75

BROKEN_WEAPON_DAMAGE_MULTIPLIER = 0.25
MAX_CONTROLLER_DT_SECONDS = 0.1

# Slots in the pinned Combat Arsenal v1 shortbow/crossbow profiles.
SHORTBOW_PRIMARY_SLOT_BASE = 0
SHORTBOW_SIGNATURE_ACTIVATE_SLOT = 5
SHORTBOW_VOLLEY_SLOT_BASE = 6
CROSSBOW_PRIMARY_SLOT = 0
CROSSBOW_SIGNATURE_ACTIVATE_SLOT = 2
CROSSBOW_BIG_ARROW_SLOT = 3
