"""Fixed capacities and failures for crowd projectile/area integration."""

from __future__ import annotations


ENTITY_IMPACTS_SCHEMA = "hytalerl_entity_impacts_v6"
ENTITY_IMPACTS_VERSION = 6

IMPACT_DAMAGE_CAPACITY = 64
PROJECTILE_PROGRAM_FAMILY_CAPACITY = 256
AREA_PROGRAM_FAMILY_CAPACITY = 256
RANGED_PROGRAM_FAMILY_CAPACITY = PROJECTILE_PROGRAM_FAMILY_CAPACITY
RANGED_PROJECTILES_PER_LAUNCH = 3
AREAS_PER_LAUNCH = 1

IMPACT_CAPABILITY_PROJECTILE_SWEEP = 1 << 0
IMPACT_CAPABILITY_WORLD_CONTACT = 1 << 1
IMPACT_CAPABILITY_EXPLOSION = 1 << 2
IMPACT_CAPABILITY_AREA_PULSE = 1 << 3
IMPACT_CAPABILITY_SOURCE_GENERATION = 1 << 4
IMPACT_CAPABILITY_CROSSBOW_ROUTING = 1 << 5
IMPACT_CAPABILITY_SEPARATE_WORLD_FAILURE = 1 << 6
IMPACT_CAPABILITY_RANGED_LAUNCH_BINDING = 1 << 7
IMPACT_CAPABILITY_RANGED_LAUNCH_ALLOCATION = 1 << 8
IMPACT_CAPABILITY_ENTITY_PROJECTILE_ALLOCATION = 1 << 9
IMPACT_CAPABILITY_ENTITY_AREA_ALLOCATION = 1 << 10
IMPACT_CAPABILITY_ENTITY_ONLY_EXPLOSION_BINDING = 1 << 11
IMPACT_CAPABILITIES = (
    IMPACT_CAPABILITY_PROJECTILE_SWEEP
    | IMPACT_CAPABILITY_WORLD_CONTACT
    | IMPACT_CAPABILITY_EXPLOSION
    | IMPACT_CAPABILITY_AREA_PULSE
    | IMPACT_CAPABILITY_SOURCE_GENERATION
    | IMPACT_CAPABILITY_CROSSBOW_ROUTING
    | IMPACT_CAPABILITY_SEPARATE_WORLD_FAILURE
    | IMPACT_CAPABILITY_RANGED_LAUNCH_BINDING
    | IMPACT_CAPABILITY_RANGED_LAUNCH_ALLOCATION
    | IMPACT_CAPABILITY_ENTITY_PROJECTILE_ALLOCATION
    | IMPACT_CAPABILITY_ENTITY_AREA_ALLOCATION
    | IMPACT_CAPABILITY_ENTITY_ONLY_EXPLOSION_BINDING
)

IMPACT_FAILURE_INVALID_STATE = 1 << 0
IMPACT_FAILURE_INVALID_DT = 1 << 1
IMPACT_FAILURE_INVALID_BINDING = 1 << 2
IMPACT_FAILURE_STALE_SOURCE = 1 << 3
IMPACT_FAILURE_QUERY = 1 << 4
IMPACT_FAILURE_AMBIGUOUS_TRIGGER = 1 << 5
IMPACT_FAILURE_DAMAGE_OVERFLOW = 1 << 6
IMPACT_FAILURE_MIXED_INTERACTION_ORDER = 1 << 7
IMPACT_FAILURE_UPSTREAM = 1 << 8
IMPACT_FAILURE_MECHANICS = 1 << 9
IMPACT_FAILURE_CROSSBOW = 1 << 10
IMPACT_FAILURE_STALE_TARGET = 1 << 11

# The World producer exposes explicit diagnostics rather than an opaque
# integer. This stable translation preserves those causes in the existing
# world-owned projectile failure domain without mixing them into Combat bits.
EXPLOSION_QUERY_FAILURE_GEOMETRY_EXHAUSTED = 1 << 0
EXPLOSION_QUERY_FAILURE_CAPACITY_EXCEEDED = 1 << 1
EXPLOSION_QUERY_FAILURE_DAMAGE_BLOCKS_UNSUPPORTED = 1 << 2
EXPLOSION_QUERY_FAILURE_INVALID = 1 << 3
