"""Fixed capacities and failure codes for multi-entity combat."""

from __future__ import annotations


COMBAT_ENTITIES_SCHEMA = "hytalerl_combat_entities_v2"
COMBAT_ENTITIES_VERSION = 2

ENTITY_CAPACITY = 32
SPAWN_CAPACITY = 8
DESPAWN_CAPACITY = 8
SELECTOR_CAPACITY = 16
ENTITY_DAMAGE_CAPACITY = 64

TEAM_NONE = -1

ENTITY_CAPABILITY_LIFECYCLE = 1 << 0
ENTITY_CAPABILITY_EXHAUSTIVE_SELECTOR = 1 << 1
ENTITY_CAPABILITY_TEAM_FILTER = 1 << 2
ENTITY_CAPABILITY_MULTI_TARGET_DAMAGE = 1 << 3
ENTITY_CAPABILITY_SHARED_COMBAT_MECHANICS = 1 << 4
ENTITY_CAPABILITY_MULTI_TARGET_STATUS = 1 << 5
ENTITY_CAPABILITIES = (
    ENTITY_CAPABILITY_LIFECYCLE
    | ENTITY_CAPABILITY_EXHAUSTIVE_SELECTOR
    | ENTITY_CAPABILITY_TEAM_FILTER
    | ENTITY_CAPABILITY_MULTI_TARGET_DAMAGE
    | ENTITY_CAPABILITY_SHARED_COMBAT_MECHANICS
    | ENTITY_CAPABILITY_MULTI_TARGET_STATUS
)

ENTITY_FAILURE_INVALID_STATE = 1 << 0
ENTITY_FAILURE_INVALID_COMMAND = 1 << 1
ENTITY_FAILURE_CAPACITY = 1 << 2
ENTITY_FAILURE_GENERATION_EXHAUSTED = 1 << 3
ENTITY_FAILURE_NATIVE_RANDOM_SUBSET = 1 << 4
ENTITY_FAILURE_DAMAGE_OVERFLOW = 1 << 5
ENTITY_FAILURE_COMBAT_MECHANICS = 1 << 6
ENTITY_FAILURE_STATUS_OVERFLOW = 1 << 7
